"use client";

import { LegalLayout, H2, P, UL, LI } from "@/app/_components/LegalLayout";

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="June 12, 2026">
      <P>
        Welcome to RealTrack. By signing up for or using our service (the &quot;Service&quot;), you agree to these Terms of Service.
        Please read them carefully. If you don&apos;t agree, don&apos;t use the Service.
      </P>

      <H2>1. The Service</H2>
      <P>
        RealTrack is a SaaS platform that ingests cold-call recordings and lead data, applies AI-based qualification,
        and presents results in a dashboard. We may add, remove, or modify features at any time.
      </P>

      <H2>2. Your Account</H2>
      <P>
        You are responsible for keeping your account credentials secure and for all activity under your account.
        You must provide accurate information and notify us immediately of any unauthorized access.
      </P>

      <H2>3. Subscription &amp; Payment</H2>
      <UL>
        <LI>Subscriptions are billed monthly in advance via bank transfer at the prices shown on our pricing page.</LI>
        <LI>Access is activated within 1–4 business hours after we receive your transfer receipt.</LI>
        <LI>Subscriptions auto-renew unless cancelled before the next billing cycle.</LI>
        <LI>Late or failed payments may result in account suspension after 7 days.</LI>
      </UL>

      <H2>4. Acceptable Use</H2>
      <P>You agree not to:</P>
      <UL>
        <LI>Upload content you don&apos;t have legal rights to (including recordings made without proper consent).</LI>
        <LI>Use the Service to send unsolicited communications or violate any anti-spam laws.</LI>
        <LI>Reverse-engineer, decompile, or attempt to extract source code from the Service.</LI>
        <LI>Resell, sublicense, or white-label the Service without an Enterprise agreement.</LI>
        <LI>Use the Service for any illegal purpose or in violation of any applicable law.</LI>
      </UL>

      <H2>5. Call Recording Consent</H2>
      <P>
        You are solely responsible for ensuring your call recordings comply with applicable consent laws
        (one-party / two-party consent jurisdictions, GDPR, etc.) in every region where calls originate or are received.
        RealTrack does not provide legal advice on call recording compliance.
      </P>

      <H2>6. Your Data</H2>
      <P>
        You own your data. We store and process it solely to provide the Service to you. We do not sell or share your data
        with third parties except as needed to deliver the Service (e.g., Google Gemini for AI analysis, Supabase for storage).
        See our <a href="/privacy" style={{ color: "#0284C7", fontWeight: 600 }}>Privacy Policy</a> for details.
      </P>

      <H2>7. Service Availability</H2>
      <P>
        We aim for 99.5% uptime but do not guarantee uninterrupted access. Scheduled maintenance, third-party outages
        (Cloudflare, Supabase, Google), and force majeure events may cause temporary downtime.
      </P>

      <H2>8. AI Output Disclaimer</H2>
      <P>
        Lead qualification scores, ARV / MAO calculations, and coaching feedback are generated by AI based on available data.
        They are <strong>informational only</strong> and should not be the sole basis for business decisions.
        You are responsible for independently verifying any AI-generated output before acting on it.
      </P>

      <H2>9. Termination</H2>
      <UL>
        <LI>You may cancel anytime by emailing <a href="mailto:info@realtrack.app" style={{ color: "#0284C7", fontWeight: 600 }}>info@realtrack.app</a>. Cancellation takes effect at the end of the current billing cycle.</LI>
        <LI>We may suspend or terminate your account for breach of these Terms, fraud, or non-payment.</LI>
        <LI>Upon termination, your data is retained for 30 days for export, then permanently deleted.</LI>
      </UL>

      <H2>10. Limitation of Liability</H2>
      <P>
        To the maximum extent permitted by law, our total liability to you for any claim related to the Service
        is limited to the amount you paid us in the 12 months preceding the claim.
        We are not liable for indirect, incidental, or consequential damages including lost profits or lost data.
      </P>

      <H2>11. Changes to These Terms</H2>
      <P>
        We may update these Terms occasionally. Material changes will be announced via email and on this page at least 14 days
        before taking effect. Continued use of the Service after changes constitutes acceptance.
      </P>

      <H2>12. Contact</H2>
      <P>
        Questions? Email <a href="mailto:info@realtrack.app" style={{ color: "#0284C7", fontWeight: 600 }}>info@realtrack.app</a>.
      </P>
    </LegalLayout>
  );
}
