"use client";

// Acquisitions & Deal Math Engine — Clean Enterprise (White / Sky / Emerald).
//   1. Retail-vs-Wholesale router badge
//   2. MAO calculator: (ARV * 0.70) - Rehab - Wholesale Fee  (money in green)
//   3. AI Handoff Dossier (sky top border, 3 bullets)
//   4. 1-click webhook export with morph-to-checkmark success animation
import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { supabase } from "@/lib/supabase";
import {
  Calculator, FileText, Send, CheckCircle2, Loader2, AlertCircle,
  Handshake, Building2, Brain, HeartCrack, DollarSign, ArrowRight,
} from "lucide-react";

const SPRING = { type: "spring", stiffness: 460, damping: 32, mass: 0.7 } as const;
const SKY = "#0EA5E9";
const SKY_600 = "#0284C7";
const MONEY = "#059669";
const money = (n: number) => `$${Math.round(Math.max(0, n)).toLocaleString()}`;

export function AcquisitionsPanel({
  leadId, address, ownerName, arv, zestimate, arvReasoning, defaultRehab, askingPrice,
  personality, painPoint, bottomLine,
}: {
  leadId: string;
  address: string | null;
  ownerName: string | null;
  arv: number;              // AI-computed ARV (from comparables)
  zestimate?: number | null; // Zillow Zestimate — market-value reference only
  arvReasoning?: string | null;
  defaultRehab: number;
  askingPrice: number | null;
  personality: string | null;
  painPoint: string | null;
  bottomLine: string | null;
}) {
  const [rehab, setRehab] = useState(defaultRehab || 0);
  const [fee, setFee] = useState(10000);

  const mao = useMemo(() => Math.max(0, arv * 0.70 - rehab - fee), [arv, rehab, fee]);

  // Router: a wholesale/cash deal needs the asking price to sit at/below MAO (room
  // to assign). If the seller wants near-retail, route to MLS.
  const route = useMemo(() => {
    if (!askingPrice || !arv) return "wholesale" as const;
    if (askingPrice <= mao * 1.08) return "wholesale" as const;
    if (askingPrice >= arv * 0.90) return "retail" as const;
    return "wholesale" as const;
  }, [askingPrice, arv, mao]);

  const generateOfferPDF = () => {
    const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>Cash Offer — ${address || "Property"}</title>
      <style>
        *{font-family:Inter,-apple-system,Segoe UI,sans-serif;color:#0F172A;box-sizing:border-box}
        body{max-width:720px;margin:40px auto;padding:0 32px}
        .bar{height:6px;background:linear-gradient(135deg,#0EA5E9,#0284C7);border-radius:6px}
        h1{font-size:26px;margin:24px 0 4px} .muted{color:#64748B;font-size:13px}
        .card{border:1px solid #E2E8F0;border-radius:14px;padding:20px;margin-top:20px}
        .row{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #F1F5F9;font-size:14px}
        .row:last-child{border-bottom:none}
        .mao{font-size:30px;font-weight:900;color:#059669}
        .sky{color:#0284C7;font-weight:800}
      </style></head><body>
      <div class="bar"></div>
      <h1>Cash Offer Summary</h1>
      <p class="muted">${today} · Prepared for ${ownerName || "Property Owner"}</p>
      <div class="card">
        <div class="row"><span>Property</span><strong>${address || "—"}</strong></div>
        ${zestimate ? `<div class="row"><span>Zestimate (Zillow)</span><strong>${money(zestimate)}</strong></div>` : ""}
        <div class="row"><span>After-Repair Value (AI estimate)</span><strong>${money(arv)}</strong></div>
        <div class="row"><span>Estimated Rehab</span><strong>${money(rehab)}</strong></div>
        <div class="row"><span>Wholesale / Assignment Fee</span><strong>${money(fee)}</strong></div>
        <div class="row"><span>Formula</span><span class="muted">(ARV × 70%) − Rehab − Fee</span></div>
        <div class="row"><span class="sky">Maximum Allowable Offer</span><span class="mao">${money(mao)}</span></div>
      </div>
      <p class="muted" style="margin-top:18px">This is a preliminary, non-binding cash offer estimate generated by RealTrack. Final offer subject to inspection and title review.</p>
      </body></html>`;
    const w = window.open("", "_blank");
    if (!w) { alert("Allow pop-ups to generate the offer PDF."); return; }
    w.document.write(html); w.document.close();
    setTimeout(() => w.print(), 350);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
      {/* ── MAO Calculator (the money UI) ── */}
      <div style={{ background: "#fff", border: "1px solid var(--border-2)", borderRadius: 18, boxShadow: "var(--shadow-sm)", overflow: "hidden" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "18px 20px", borderBottom: "1px solid var(--border-1)", flexWrap: "wrap" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span style={{ width: 32, height: 32, borderRadius: 9, background: "var(--grad-primary)", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <Calculator size={16} color="#fff" />
            </span>
            <div>
              <p style={{ fontSize: 15, fontWeight: 800, color: "var(--text-1)" }}>Deal Math · MAO Calculator</p>
              <p style={{ fontSize: 11, color: "var(--text-3)" }}>Maximum Allowable Offer at the 70% rule</p>
            </div>
          </div>
          <RouterBadge route={route} />
        </div>

        <div style={{ padding: 20, display: "grid", gridTemplateColumns: "minmax(0,1.1fr) minmax(0,0.9fr)", gap: 20 }} className="ci-grid">
          {/* Inputs */}
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <ReadRow label="Zestimate (Zillow)" value={zestimate ? money(zestimate) : "—"} sub="Market-value reference" />
            <ReadRow label="AI-Estimated ARV" value={arv ? money(arv) : "—"} sub={arvReasoning || "Computed from comparable sales"} accent={SKY_600} />
            <NumberRow label="AI-Estimated Rehab Cost" value={rehab} onChange={setRehab} />
            <NumberRow label="Wholesale / Assignment Fee" value={fee} onChange={setFee} />
            <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--text-3)", paddingTop: 4 }}>
              <span style={{ fontWeight: 700, color: SKY_600 }}>(ARV × 0.70)</span> − Rehab − Fee
            </div>
          </div>

          {/* MAO result */}
          <div style={{
            borderRadius: 14, padding: 20, display: "flex", flexDirection: "column", justifyContent: "center",
            background: "var(--money-soft)", border: "1px solid color-mix(in srgb, #059669 30%, transparent)",
          }}>
            <p style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.06em", textTransform: "uppercase", color: MONEY, display: "inline-flex", alignItems: "center", gap: 5 }}>
              <DollarSign size={12} /> Maximum Allowable Offer
            </p>
            <motion.p key={mao} initial={{ scale: 0.92, opacity: 0.4 }} animate={{ scale: 1, opacity: 1 }} transition={SPRING}
              style={{ fontSize: 38, fontWeight: 900, color: MONEY, letterSpacing: "-0.02em", lineHeight: 1.05, margin: "6px 0 2px" }}>
              {money(mao)}
            </motion.p>
            {askingPrice ? (
              <p style={{ fontSize: 12, color: "var(--text-3)" }}>
                Seller asking <strong style={{ color: "var(--text-1)" }}>{money(askingPrice)}</strong>
                {askingPrice <= mao ? " · spread in your favor" : ` · ${money(askingPrice - mao)} over MAO`}
              </p>
            ) : null}
            <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} onClick={generateOfferPDF}
              style={{
                marginTop: 14, padding: "10px 14px", borderRadius: 10, border: "none", cursor: "pointer",
                background: "var(--grad-primary)", color: "#fff", fontSize: 12.5, fontWeight: 800,
                display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 7,
                boxShadow: "0 8px 20px color-mix(in srgb, #0EA5E9 35%, transparent)",
              }}>
              <FileText size={14} /> Generate Offer PDF
            </motion.button>
          </div>
        </div>
      </div>

      {/* ── AI Handoff Dossier ── */}
      {(personality || painPoint || bottomLine) && (
        <div style={{ background: "#fff", border: "1px solid var(--border-2)", borderTop: `3px solid ${SKY}`, borderRadius: 16, padding: 20, boxShadow: "var(--shadow-sm)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
            <span style={{ width: 30, height: 30, borderRadius: 8, background: "color-mix(in srgb, #0EA5E9 14%, transparent)", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <Brain size={15} color={SKY_600} />
            </span>
            <p style={{ fontSize: 15, fontWeight: 800, color: "var(--text-1)" }}>AI Handoff Dossier</p>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            <DossierRow icon={Brain} label="Personality" value={personality} />
            <DossierRow icon={HeartCrack} label="Pain Point" value={painPoint} />
            <DossierRow icon={DollarSign} label="Bottom-Line Price" value={bottomLine} money />
          </div>
        </div>
      )}

      {/* ── 1-Click Webhook Export ── */}
      <WebhookExport leadId={leadId} />
    </div>
  );
}

function RouterBadge({ route }: { route: "wholesale" | "retail" }) {
  const wholesale = route === "wholesale";
  const c = wholesale ? MONEY : SKY_600;
  const Icon = wholesale ? Handshake : Building2;
  return (
    <span style={{
      display: "inline-flex", alignItems: "center", gap: 7, padding: "6px 13px", borderRadius: 999,
      background: `color-mix(in srgb, ${c} 12%, transparent)`, color: c,
      border: `1px solid color-mix(in srgb, ${c} 35%, transparent)`, fontSize: 12, fontWeight: 800,
    }}>
      <Icon size={13} /> {wholesale ? "Wholesale / Cash Deal" : "Retail / MLS"}
    </span>
  );
}

function ReadRow({ label, value, sub, accent }: { label: string; value: string; sub?: string; accent?: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, padding: "11px 14px", borderRadius: 10, background: "var(--surface-3)", border: "1px solid var(--border-1)" }}>
      <div style={{ minWidth: 0 }}>
        <span style={{ fontSize: 12.5, color: "var(--text-2)", fontWeight: 600 }}>{label}</span>
        {sub && <p style={{ fontSize: 10.5, color: "var(--text-3)", marginTop: 2, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{sub}</p>}
      </div>
      <span style={{ fontSize: 15, fontWeight: 800, color: accent || "var(--text-1)", flexShrink: 0 }}>{value}</span>
    </div>
  );
}

function NumberRow({ label, value, onChange }: { label: string; value: number; onChange: (n: number) => void }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "9px 14px", borderRadius: 10, background: "#fff", border: "1px solid var(--border-2)" }}>
      <span style={{ fontSize: 12.5, color: "var(--text-2)", fontWeight: 600 }}>{label}</span>
      <div style={{ display: "inline-flex", alignItems: "center", gap: 2 }}>
        <span style={{ fontSize: 14, fontWeight: 800, color: "var(--text-3)" }}>$</span>
        <input type="number" min={0} step={500} value={value}
          onChange={(e) => onChange(Math.max(0, Number(e.target.value) || 0))}
          style={{ width: 96, textAlign: "right", padding: "5px 8px", borderRadius: 8, border: "1px solid var(--border-2)", background: "var(--surface-3)", color: "var(--text-1)", fontSize: 14, fontWeight: 800, outline: "none" }} />
      </div>
    </div>
  );
}

function DossierRow({ icon: Icon, label, value, money: isMoney }: { icon: React.ComponentType<{ size?: number; color?: string }>; label: string; value: string | null; money?: boolean }) {
  return (
    <div style={{ display: "flex", gap: 11, alignItems: "flex-start" }}>
      <span style={{ width: 26, height: 26, borderRadius: 7, flexShrink: 0, background: "var(--surface-3)", display: "flex", alignItems: "center", justifyContent: "center", marginTop: 1 }}>
        <Icon size={13} color={isMoney ? MONEY : SKY_600} />
      </span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <p style={{ fontSize: 10, fontWeight: 800, letterSpacing: "0.05em", textTransform: "uppercase", color: "var(--text-3)" }}>{label}</p>
        <p style={{ fontSize: 13.5, lineHeight: 1.5, fontWeight: isMoney ? 800 : 500, color: isMoney ? MONEY : "#000" }}>
          {value || "Not captured on the call."}
        </p>
      </div>
    </div>
  );
}

type ExportState = "idle" | "sending" | "done" | "error";
function WebhookExport({ leadId }: { leadId: string }) {
  const [state, setState] = useState<ExportState>("idle");
  const [err, setErr] = useState("");

  const fire = async () => {
    if (state === "sending" || state === "done") return;
    setState("sending");
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const r = await fetch(`/api/leads/${leadId}/export`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${session?.access_token}` },
        body: JSON.stringify({}),
      });
      const j = await r.json().catch(() => ({}));
      if (!r.ok || !j.ok) throw new Error(j.error || "Webhook failed");
      setState("done");
      setTimeout(() => setState("idle"), 3200);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Failed");
      setState("error");
      setTimeout(() => setState("idle"), 3500);
    }
  };

  const done = state === "done";
  return (
    <motion.button
      onClick={fire}
      disabled={state === "sending"}
      animate={{ backgroundColor: done ? MONEY : state === "error" ? "#DC2626" : SKY }}
      transition={SPRING}
      whileHover={state === "idle" ? { scale: 1.01 } : undefined}
      whileTap={state === "idle" ? { scale: 0.99 } : undefined}
      style={{
        position: "relative", width: "100%", padding: "14px 18px", borderRadius: 12, border: "none",
        cursor: state === "sending" ? "wait" : "pointer", color: "#fff", fontSize: 14, fontWeight: 800,
        display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 9,
        boxShadow: `0 10px 26px color-mix(in srgb, ${done ? MONEY : SKY} 40%, transparent)`,
        overflow: "hidden",
      }}>
      <AnimatePresence mode="wait" initial={false}>
        {state === "idle" && (
          <motion.span key="idle" initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.18 }} style={{ display: "inline-flex", alignItems: "center", gap: 9 }}>
            <Send size={16} /> Export to Acquisitions CRM <ArrowRight size={15} />
          </motion.span>
        )}
        {state === "sending" && (
          <motion.span key="send" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.15 }} style={{ display: "inline-flex", alignItems: "center", gap: 9 }}>
            <Loader2 size={16} className="animate-spin" /> Routing JSON…
          </motion.span>
        )}
        {state === "done" && (
          <motion.span key="done" initial={{ opacity: 0, scale: 0.6 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} transition={SPRING} style={{ display: "inline-flex", alignItems: "center", gap: 9 }}>
            <motion.span initial={{ scale: 0, rotate: -30 }} animate={{ scale: 1, rotate: 0 }} transition={{ ...SPRING, delay: 0.05 }}>
              <CheckCircle2 size={18} />
            </motion.span>
            Routed to CRM
          </motion.span>
        )}
        {state === "error" && (
          <motion.span key="err" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ display: "inline-flex", alignItems: "center", gap: 9 }}>
            <AlertCircle size={16} /> {err || "Export failed"}
          </motion.span>
        )}
      </AnimatePresence>
    </motion.button>
  );
}
